language: node_js
node_js:
  - "node"
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master

